channels:
  - conda-forge
dependencies:
  - r-base=4.0.2
  - r-tidyverse
  - r-knitr
  - r-tidymodels
  - r-kernlab
  - r-kknn
  - r-glmnet
  - r-leaps
  - r-car
  - r-mlbench
  - r-skimr
  - r-klar
  - r-rpart
  - r-rpart.plot
  - r-xgboost
  - r-randomforest
  - r-vip
  - r-keras
  - r-tensorflow
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-image
  - scikit-learn
  - scipy
